AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  CerberusBot

  Discord Interactions bot written in Kotlin and Python

Resources:
  CerberusBotDeferFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: sam/defer/defer
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - arm64
      MemorySize: 512
      Timeout: 3
      Environment:
        Variables:
          INTERACT_FUNCTION: !Ref CerberusBotInteractFunction
          PUBLIC_KEY:
            Ref: PublicKeyParameter
      Events:
        DiscordInteraction:
          Type: HttpApi
          Properties:
            Path: /
            Method: post
      Policies:
        - Statement:
            - Sid: Interact
              Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource: !GetAtt CerberusBotInteractFunction.Arn
  CerberusBotInteractFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: sam/interact
      Handler: cloud.drakon.cerberusbot.interact.Handler::handleRequest
      Runtime: java17
      Architectures:
        - arm64
      MemorySize: 2048
      Timeout: 900
      Environment:
        Variables:
          APPLICATION_ID:
            Ref: ApplicationIDParameter
          BOT_TOKEN:
            Ref: BotTokenParameter
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=0
          PUBLIC_KEY:
            Ref: PublicKeyParameter
          MONGODB_URL:
            Ref: MongoDbUrl
          MONGODB_DATABASE:
            Ref: MongoDbDatabase
      Policies:
        - Statement:
            - Sid: Translate
              Effect: Allow
              Action:
                - translate:TranslateText
                - comprehend:DetectDominantLanguage
              Resource: "*"

Outputs:
  CerberusBot:
    Description: "API Gateway endpoint URL for CerberusBot Defer function"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com"

  CerberusBotDeferFunction:
    Description: "CerberusBot Defer Lambda Function ARN"
    Value: !GetAtt CerberusBotDeferFunction.Arn
  CerberusBotDeferFunctionIamRole:
    Description: "Implicit IAM Role created for CerberusBot Defer function"
    Value: !GetAtt CerberusBotDeferFunctionRole.Arn

  CerberusBotInteractFunction:
    Description: "CerberusBot Interact Lambda Function ARN"
    Value: !GetAtt CerberusBotInteractFunction.Arn
  CerberusBotInteractFunctionIamRole:
    Description: "Implicit IAM Role created for CerberusBot Interact function"
    Value: !GetAtt CerberusBotInteractFunctionRole.Arn

Parameters:
  ApplicationIDParameter:
    Type: String
    NoEcho: True
  BotTokenParameter:
    Type: String
    NoEcho: True
  PublicKeyParameter:
    Type: String
    NoEcho: True
  MongoDbUrl:
    Type: String
    NoEcho: True
  MongoDbDatabase:
    Type: String
    NoEcho: True
    Default: cerberusbot
