AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  DynamisBot

  Discord Interactions bot written in Kotlin and Python

Resources:
  DynamisBotDeferFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bot/defer/defer
      Handler: app.lambda_handler
      Runtime: python3.10
      Architectures:
        - arm64
      MemorySize: 512
      Timeout: 3
      Environment:
        Variables:
          EORZEADATABASE_FUNCTION: !Ref DynamisBotEorzeaDatabaseFunction
          LODESTONE_FUNCTION: !Ref DynamisBotLodestoneFunction
          UNIVERSALIS_FUNCTION: !Ref DynamisBotUniversalisFunction
          PUBLIC_KEY:
            Ref: PublicKeyParameter
      Events:
        DiscordInteraction:
          Type: HttpApi
          Properties:
            Path: /
            Method: post
      Policies:
        - Statement:
            - Sid: Interact
              Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource:
                - !GetAtt DynamisBotEorzeaDatabaseFunction.Arn
                - !GetAtt DynamisBotLodestoneFunction.Arn
                - !GetAtt DynamisBotUniversalisFunction.Arn
  DynamisBotEorzeaDatabaseFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bot/commands/eorzeadatabase
      Handler: cloud.drakon.dynamisbot.eorzeadatabase.Handler::handleRequest
      Runtime: java17
      Architectures:
        - x86_64
      MemorySize: 512
      Timeout: 900
      AutoPublishAlias: SnapStart
      SnapStart:
        ApplyOn: PublishedVersions
      Environment:
        Variables:
          APPLICATION_ID:
            Ref: ApplicationIDParameter
          BOT_TOKEN:
            Ref: BotTokenParameter
          PUBLIC_KEY:
            Ref: PublicKeyParameter
  DynamisBotLodestoneFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bot/commands/lodestone
      Handler: cloud.drakon.dynamisbot.lodestone.Handler::handleRequest
      Runtime: java17
      Architectures:
        - x86_64
      MemorySize: 512
      Timeout: 900
      AutoPublishAlias: SnapStart
      SnapStart:
        ApplyOn: PublishedVersions
      Environment:
        Variables:
          APPLICATION_ID:
            Ref: ApplicationIDParameter
          BOT_TOKEN:
            Ref: BotTokenParameter
          PUBLIC_KEY:
            Ref: PublicKeyParameter
          MONGODB_URL:
            Ref: MongoDbUrl
          MONGODB_DATABASE:
            Ref: MongoDbDatabase
  DynamisBotUniversalisFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bot/commands/universalis
      Handler: cloud.drakon.dynamisbot.universalis.Handler::handleRequest
      Runtime: java17
      Architectures:
        - x86_64
      MemorySize: 512
      Timeout: 900
      AutoPublishAlias: SnapStart
      SnapStart:
        ApplyOn: PublishedVersions
      Environment:
        Variables:
          APPLICATION_ID:
            Ref: ApplicationIDParameter
          BOT_TOKEN:
            Ref: BotTokenParameter
          PUBLIC_KEY:
            Ref: PublicKeyParameter

Outputs:
  DynamisBot:
    Description: "API Gateway endpoint URL for DynamisBot Defer function"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com"

  DynamisBotLodestoneFunctionIamRole:
    Description: "Implicit IAM Role created for DynamisBot Lodestone function"
    Value: !GetAtt DynamisBotLodestoneFunctionRole.Arn

Parameters:
  ApplicationIDParameter:
    Type: String
    NoEcho: True
  BotTokenParameter:
    Type: String
    NoEcho: True
  PublicKeyParameter:
    Type: String
    NoEcho: True
  MongoDbUrl:
    Type: String
    NoEcho: True
  MongoDbDatabase:
    Type: String
    NoEcho: True
    Default: dynamisbot
