AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  DynamisBot

  Discord Interactions bot written in Kotlin and Python

Resources:
  DynamisBotDeferFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bot/defer/defer
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - arm64
      MemorySize: 512
      Timeout: 3
      Environment:
        Variables:
          INTERACT_FUNCTION: !Ref DynamisBotInteractFunction
          PUBLIC_KEY:
            Ref: PublicKeyParameter
      Events:
        DiscordInteraction:
          Type: HttpApi
          Properties:
            Path: /
            Method: post
      Policies:
        - Statement:
            - Sid: Interact
              Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource: !GetAtt DynamisBotInteractFunction.Arn
  DynamisBotInteractFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bot/interact
      Handler: cloud.drakon.dynamisbot.interact.Handler::handleRequest
      Runtime: java17
      Architectures:
        - arm64
      MemorySize: 2048
      Timeout: 900
      Environment:
        Variables:
          APPLICATION_ID:
            Ref: ApplicationIDParameter
          BOT_TOKEN:
            Ref: BotTokenParameter
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=0
          PUBLIC_KEY:
            Ref: PublicKeyParameter
          MONGODB_URL:
            Ref: MongoDbUrl
          MONGODB_DATABASE:
            Ref: MongoDbDatabase
      Policies:
        - Statement:
            - Sid: Translate
              Effect: Allow
              Action:
                - translate:TranslateText
                - comprehend:DetectDominantLanguage
              Resource: "*"

Outputs:
  DynamisBot:
    Description: "API Gateway endpoint URL for DynamisBot Defer function"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com"

  DynamisBotDeferFunction:
    Description: "DynamisBot Defer Lambda Function ARN"
    Value: !GetAtt DynamisBotDeferFunction.Arn
  DynamisBotDeferFunctionIamRole:
    Description: "Implicit IAM Role created for DynamisBot Defer function"
    Value: !GetAtt DynamisBotDeferFunctionRole.Arn

  DynamisBotInteractFunction:
    Description: "DynamisBot Interact Lambda Function ARN"
    Value: !GetAtt DynamisBotInteractFunction.Arn
  DynamisBotInteractFunctionIamRole:
    Description: "Implicit IAM Role created for DynamisBot Interact function"
    Value: !GetAtt DynamisBotInteractFunctionRole.Arn

Parameters:
  ApplicationIDParameter:
    Type: String
    NoEcho: True
  BotTokenParameter:
    Type: String
    NoEcho: True
  PublicKeyParameter:
    Type: String
    NoEcho: True
  MongoDbUrl:
    Type: String
    NoEcho: True
  MongoDbDatabase:
    Type: String
    NoEcho: True
    Default: dynamisbot
